import { defineConfig } from "@doclient/cli";
import { createGoRenderer } from "@doclient/renderer-go";
import { lazadaProfile } from "./profile.js";
import { lazadaSource } from "./source-lazada.js";

export default defineConfig({
  name: "go-lazada-v1",
  source: lazadaSource,
  output: createGoRenderer(lazadaProfile, {
    package: "golazada",
    module: "github.com/naputt1/lazada-go",
  }),
  outputDir: ".",
  cacheDir: ".cache/lazada",
  mappings: {
    typeOverrides: {
      item_id: "int64",
      seller_id: "int64",
      shop_id: "int64",
      order_id: "int64",
      order_item_id: "int64",
      product_id: "int64",
      sku_id: "int64",
      category_id: "int64",
      primary_category: "int64",
      page_size: "int64",
      page_index: "int64",
      offset: "int64",
      limit: "int64",
      total: "int64",
      total_products: "int64",
      total_count: "int64",
      is_active: "bool",
      is_activated: "bool",
      success: "bool",
      status: "string",
      brand_id: "int64",
      id: "int64",
      start_row: "int64",
      total_page: "int64",
      total_record: "int64",
      enable_total: "bool",
      is_mandatory: "int64",
      is_sale_prop: "int64",
      is_key_prop: "int64",
      var: "bool",
      leaf: "bool",
      images: "[]string",
      price: "float64",
      trialProduct: "bool",
      marketImages: "[]string",
    },
    ignoreAPIs: [],
    staticModules: [],
  },
});
