package golazada

const (
	Err00                                  = "00"                                       // sucess
	Err01                                  = "01"                                       // cancel success
	Err02                                  = "02"                                       // update serviceDate success
	Err100                                 = "100"                                      // E0100: reverse order list is empty
	Err1000012                             = "1000012"                                  // endTime - startTime must should be less than 180 days
	Err1000014                             = "1000014"                                  // Can not find that transactionType
	Err10001                               = "10001"                                    // Illegal parameters
	Err10002                               = "10002"                                    // System error
	Err10003                               = "10003"                                    // Item not found
	Err10004                               = "10004"                                    // price need to be lower than the original price
	Err10005                               = "10005"                                    // 商品已升级
	Err10006                               = "10006"                                    // 商品校验失败，无法升级
	Err1003                                = "1003"                                     // E1003_3PL_ALLOCATION_FAIL
	Err101                                 = "101"                                      // E101: Redemption Operator Invalid
	Err102                                 = "102"                                      // E0102: trade order line id is empty or invalid
	Err103                                 = "103"                                      // E0103: reverse order line id is empty when query reject reason
	Err104                                 = "104"                                      // E0104: reason is empty or invalid
	Err105                                 = "105"                                      // E0105: reverse order id is empty or invalid
	Err106                                 = "106"                                      // E0106: ROC internal error
	Err107                                 = "107"                                      // E0107: invalid action
	Err108                                 = "108"                                      // E0108: reason can't be empty if you want to refuse return or refund
	Err109                                 = "109"                                      // E0109: comment can't be empty if startDispute
	Err11                                  = "11"                                       // orderNo is empty
	Err110                                 = "110"                                      // E0110: image can't be empty if startDispute
	Err111                                 = "111"                                      // E0111: do not support massive reverse order line operation if you want to refuse return or refund
	Err112                                 = "112"                                      // E0112: no reverse order found
	Err113                                 = "113"                                      // E0113: reverse order line have unknown status
	Err114                                 = "114"                                      // E0114: this reverse does not support this action
	Err115                                 = "115"                                      // E0115: order id is null
	Err116                                 = "116"                                      // E0116: no seller id
	Err117                                 = "117"                                      // E0117: no user id
	Err118                                 = "118"                                      // E0118: no user email
	Err119                                 = "119"                                      // E0119: cannot find any cancel reasons for these orders
	Err12                                  = "12"                                       // thirdOrderNo is empty
	Err120                                 = "120"                                      // E0120: page size invalid
	Err121                                 = "121"                                      // E0121: page number invalid
	Err122                                 = "122"                                      // E0122: invalid trade order
	Err123                                 = "123"                                      // E0123: invalid trade order lines %s
	Err124                                 = "124"                                      // E0124: invalid seller id for this order line %s
	Err125                                 = "125"                                      // E0125: invalid reverse id
	Err126                                 = "126"                                      // E0126: invalid reverse order lines
	Err127                                 = "127"                                      // E0127: invalid seller id for this reverse order line
	Err13                                  = "13"                                       // type is empty
	Err131                                 = "131"                                      // E0131: no decision for this reverse order
	Err133                                 = "133"                                      // E0133: do not support batch operation
	Err14                                  = "14"                                       // E014: "%s" Invalid Offset
	Err15                                  = "15"                                       // servicePrice is empty
	Err16                                  = "16"                                       // E016: "%s" Invalid Order ID
	Err17                                  = "17"                                       // E017: "%s" Invalid Date Format
	Err19                                  = "19"                                       // E019: Invalid Limit
	Err20                                  = "20"                                       // E020: "%s" Invalid Order Item IDs
	Err200                                 = "200"                                      // E200: Certificate Not Exist
	Err201                                 = "201"                                      // E201: Certificate Not Unique
	Err202                                 = "202"                                      // E202: Certificate Can Not Distinguish
	Err203                                 = "203"                                      // E203: Certificate Order Not Exist
	Err21                                  = "21"                                       // E021: Internal System Error
	Err22                                  = "22"                                       // E022: "%s"
	Err23                                  = "23"                                       // E023: activate failed
	Err24                                  = "24"                                       // E024: Parameter illegal
	Err25                                  = "25"                                       // E025: UMP Exception
	Err26                                  = "26"                                       // E026: Seller Unauthorized
	Err30012                               = "30012"                                    // rts package not found
	Err301                                 = "301"                                      // E301: Certificate Not Available
	Err306                                 = "306"                                      // E306: attribute tag not allowed
	Err309                                 = "309"                                      // Video id status is not audit success
	Err31                                  = "31"                                       // parse extendInfo to map fail
	Err32                                  = "32"                                       // E032: Document type "%s" is not valid
	Err34                                  = "34"                                       // E034: Order Item must be packed. Please call SetStatusToReadyToShip before
	Err35                                  = "35"                                       // E035: "%s" was not found
	Err36                                  = "36"                                       // E036: Invalid status filter
	Err37                                  = "37"                                       // E037: One or more order id in the list are incorrect
	Err38                                  = "38"                                       // E038: Too many orders were requested
	Err39                                  = "39"                                       // E039: No orders were found
	Err40011                               = "40011"                                    // RPC_ERROR
	Err4136                                = "4136"                                     // SYSTEM_BUSY
	Err4137                                = "4137"                                     // SYSTEM_TIMEOUT
	Err4138                                = "4138"                                     // SYSTEM_EXCEPTION
	Err4139                                = "4139"                                     // UNKNOWN_ERROR
	Err4140                                = "4140"                                     // CATEGORY_CANNOT_FIND
	Err4141                                = "4141"                                     // CATEGORY_NOT_PERMITTED
	Err4142                                = "4142"                                     // CATEGORY_IS_INACTIVE
	Err4143                                = "4143"                                     // NO_TARGET_USER_BIND
	Err4144                                = "4144"                                     // LOCAL_CATEGORY_CANNOT_FIND
	Err4145                                = "4145"                                     // GLOBAL_PRODUCT_CANNOT_FIND
	Err4146                                = "4146"                                     // LOCAL_PRODUCT_CANNOT_FIND
	Err4147                                = "4147"                                     // LOCAL_SKU_CANNOT_FIND
	Err4148                                = "4148"                                     // LOCAL_PRODUCT_HAS_NOT_BEEN_SYNCED
	Err4149                                = "4149"                                     // LOCAL_SKU_HAS_NOT_BEEN_SYNCED
	Err4150                                = "4150"                                     // PRODUCT_DOES_NOT_BELONG_TO_USER
	Err4151                                = "4151"                                     // DAO_NOT_SUPPORT_BIZ_TYPE
	Err4152                                = "4152"                                     // DAO_GLOBAL_PDT_NOT_FOUND
	Err4153                                = "4153"                                     // DAO_GLOBAL_SKU_NOT_FOUND
	Err4154                                = "4154"                                     // DAO_LOCAL_ITEM_RELATION_NOT_FOUND
	Err4155                                = "4155"                                     // DAO_LOCAL_SKU_RELATION_NOT_FOUND
	Err4156                                = "4156"                                     // NO_CREATE_PRODUCT_PERMISSION
	Err4157                                = "4157"                                     // PRICE_GENERAL_TOO_LOW_ERROR
	Err4158                                = "4158"                                     // PRICE_GENERAL_TOO_HIGH_ERROR
	Err4159                                = "4159"                                     // PRICE_GENERAL_DISCOUNT_TOO_HIGH_ERROR
	Err4160                                = "4160"                                     // PRICE_GENERAL_DISCOUNT_TOO_LOW_ERROR
	Err4161                                = "4161"                                     // PB_SALE_PROP_RENDER_ILLEGAL_SALE_PROP
	Err4162                                = "4162"                                     // PB_SKU_DESC_RENDER_ILLEGAL_SKU_DESC
	Err4163                                = "4163"                                     // PB_VENTURE_NO_VENTURE_SELECT
	Err4164                                = "4164"                                     // PB_VENTURE_MY_NOT_PUBLISHED
	Err4165                                = "4165"                                     // PB_NAME_NAME_CANNOT_BE_NULL
	Err4166                                = "4166"                                     // PB_NAME_NAME_CANNOT_BE_TOO_LONG
	Err4167                                = "4167"                                     // PB_NAME_NAME_TRAN_TOO_LONG
	Err4168                                = "4168"                                     // PB_BRAND_ILLEGAL
	Err4169                                = "4169"                                     // PB_DETAIL_ATTRIBUTE_REQUIRED
	Err4170                                = "4170"                                     // PB_SHORTDESC_REQUIRED
	Err4171                                = "4171"                                     // PB_DETAIL_LENGTH_ERROR
	Err4172                                = "4172"                                     // PB_SKU_PROP_REQUIRED
	Err4173                                = "4173"                                     // PB_NO_PROPER_SKU
	Err4174                                = "4174"                                     // PB_NO_PC_DECO
	Err4175                                = "4175"                                     // PB_NO_WIRELESS_DECO
	Err4176                                = "4176"                                     // PB_IMG_CANNOT_BE_EMPTY
	Err4177                                = "4177"                                     // PB_IMG_URL_INVALID
	Err4178                                = "4178"                                     // PB_IMG_CANNOT_FETCH
	Err4179                                = "4179"                                     // PB_SALE_PROP_SUBMIT_SALE_PROP_CANNOT_BE_EMPTY
	Err4180                                = "4180"                                     // PB_SALE_PROP_SUBMIT_SALE_PROP_ILLEGAL_VAL
	Err4181                                = "4181"                                     // PB_SALE_PROP_SUBMIT_SALE_PROP_INVALID_INPUT_VAL
	Err4182                                = "4182"                                     // PB_SALE_PROP_SUBMIT_SALE_PROP_TOO_LONG_INPUT_VAL
	Err4183                                = "4183"                                     // PB_SALE_PROP_SUBMIT_TOO_MORE_SKU
	Err4184                                = "4184"                                     // PB_CURRENCY_CANNOT_BE_EMPTY
	Err4185                                = "4185"                                     // PB_ORIGIN_PRICE_CANNOT_BE_EMPTY
	Err4186                                = "4186"                                     // PB_ORIGIN_SALE_PRICE_CANNOT_BE_EMPTY
	Err4187                                = "4187"                                     // PB_ORIGIN_SALE_PRICE_CANNOT_BE_HIGH
	Err4188                                = "4188"                                     // PB_MARKET_PRICE_CANNOT_BE_EMPTY
	Err4189                                = "4189"                                     // PB_MARKET_SALE_PRICE_CANNOT_BE_EMPTY
	Err4190                                = "4190"                                     // PB_MARKET_SALE_PRICE_TOO_HIGH
	Err4191                                = "4191"                                     // PB_STOCK_CANNOT_BE_EMPTY
	Err4192                                = "4192"                                     // PB_STOCK_INVALID
	Err4193                                = "4193"                                     // PB_WARRANTY_INVALID
	Err4194                                = "4194"                                     // PB_SELLER_SKU_EXIST
	Err4195                                = "4195"                                     // PB_SELLER_SKU_LENGTH_ERROR
	Err4196                                = "4196"                                     // PB_SELLER_SKU_DUPLICATE
	Err4197                                = "4197"                                     // PB_SELLER_SKU_INVALID
	Err4198                                = "4198"                                     // PB_SELLER_SKU_CANNOT_BE_REVISED
	Err4199                                = "4199"                                     // PB_PACKAGE_UNMATCHED
	Err4200                                = "4200"                                     // IMAP_BRAND_NOT_MATCHED
	Err4201                                = "4201"                                     // IMAP_SALE_PROP_UNMATCHED
	Err4202                                = "4202"                                     // IMAP_SALE_PROP_ERR_MATCHED
	Err4203                                = "4203"                                     // IMAP_DEST_SALE_PROP_IS_SPU
	Err4204                                = "4204"                                     // IMAP_SALE_PROP_VAL_ERR_MATCHED
	Err4205                                = "4205"                                     // INVALID_IMAGE_FORMAT
	Err4206                                = "4206"                                     // INVALID_IMAGE_DIMENSION
	Err4207                                = "4207"                                     // IMPORT_SELLER_SKU_EMPTY
	Err4208                                = "4208"                                     // IMPORT_SELLER_SKU_INVALID
	Err4209                                = "4209"                                     // INVALID_CATEGORY
	Err4210                                = "4210"                                     // FAIL_TO_GET_CATEGORY_ID
	Err4211                                = "4211"                                     // HAZMAT_WARN
	Err4212                                = "4212"                                     // PDT_LIMIT_REACH
	Err4213                                = "4213"                                     // MIGRAGE_IMAGE_FAILED
	Err4214                                = "4214"                                     // PG_NOT_PERMIT
	Err4215                                = "4215"                                     // DECO_CREATE_ERROR
	Err4216                                = "4216"                                     // DECO_NO_TARGET_USER_BIND
	Err4217                                = "4217"                                     // DECO_SOURCE_QUERY_ERROR
	Err4218                                = "4218"                                     // DECO_TRANSLATE_ERROR
	Err4219                                = "4219"                                     // DECO_SYNC_ERROR
	Err4220                                = "4220"                                     // TRANSLATE_OVER_FLOW
	Err4221                                = "4221"                                     // ITEM_NEVER_PUBLISH_SUCCESSED
	Err4222                                = "4222"                                     // NO_SKU_COULD_BE_UPDATE
	Err4223                                = "4223"                                     // PRODUCT_NUM_REACH_LIMITATION
	Err4224                                = "4224"                                     // SELLER_STATUS_INVALID
	Err4225                                = "4225"                                     // PRICE_NOT_VALID
	Err4226                                = "4226"                                     // SELLER_PUNISHMENT_INVALID
	Err4227                                = "4227"                                     // SKU_IMAGE_INVALID
	Err4228                                = "4228"                                     // PRODUCT_IMAGE_INVALID
	Err4229                                = "4229"                                     // PROHIBITED_BRAND
	Err4230                                = "4230"                                     // PROHIBITED_KEYWORD
	Err5                                   = "5"                                        // "E005: Invalid Request Format"
	Err500                                 = "500"                                      // "E500: Create product failed"
	Err50008                               = "50008"                                    // ot support operation for sof order
	Err501                                 = "501"                                      // E501: Update product failed
	Err56                                  = "56"                                       // E056: Invalid OrdersIdList format. Must use array format [1,2]
	Err6                                   = "6"                                        // "E006: Unexpected internal error"
	Err700000                              = "700000"                                   // PACKAGE_STATUS_NOT_ALLOW_TO_OP
	Err700001                              = "700001"                                   // DBS_SHIPMENT_PROVIDER_CODE_NOT_EXITS
	Err700004                              = "700004"                                   //  PARAM_ILLEGAL
	Err700013                              = "700013"                                   // OP_NOT_SUPPORT
	Err700016                              = "700016"                                   // NOT_AVAILABLE_NTFS_3PL
	Err700017                              = "700017"                                   // PARAM_IS_NULL
	Err700018                              = "700018"                                   //  PARAM_SIZE_ERROR
	Err700019                              = "700019"                                   // PARAM_MIN_ERROR
	Err700020                              = "700020"                                   // ORDER_ITEM_NOT_FOUND_OR_NOT_BELONG_DIGITAL
	Err700021                              = "700021"                                   //  ORDER_NOT_FOUND
	Err700022                              = "700022"                                   // BATCH_SIZE_OUT_OF_LIMIT
	Err700023                              = "700023"                                   //  PICKUP_IN_STORE_NO_SUPPORT
	Err700024                              = "700024"                                   // GET_LOCK_FAILED
	Err700025                              = "700025"                                   // ORDER_ITEM_NOT_FOUND
	Err700026                              = "700026"                                   // FO_ITEM_NOT_ALLOW_TO_PACK
	Err700027                              = "700027"                                   // NOT_SUPPORT_FBL_TO_PACK
	Err700028                              = "700028"                                   // NOT_SUPPORT_PACK_UP_IN_STORE_TO_PACK
	Err700029                              = "700029"                                   //  ITEM_MUST_BELONG_SAME_WAREHOUSE
	Err700030                              = "700030"                                   //  NOT_SUPPORT_DG_SERVICE_TO_PACK
	Err700031                              = "700031"                                   //  ITEM_NOT_READY_TO_FULFILL
	Err700032                              = "700032"                                   // SELLER_NOT_FOUND
	Err700033                              = "700033"                                   // TRANSFERRING_WAREHOUSE_PROVIDER
	Err700040                              = "700040"                                   // There are no packages that support printing!
	Err74                                  = "74"                                       // E074: Invalid sort direction.
	Err75                                  = "75"                                       // E075: Invalid sort filter.
	Err99                                  = "99"                                       // fail
	ErrAPPKEYINVALID                       = "APP_KEY_INVALID"                          // App key is invalid, please contact lazada tech team.
	ErrBADREQUEST                          = "BAD_REQUEST"                              // Invalid request
	ErrBALANCEACCOUNTNOTENOUGH             = "BALANCE_ACCOUNT_NOT_ENOUGH"               // Balance account is not enough.
	ErrBATCHCREATEERROR                    = "BATCH_CREATE_ERROR"                       // Error happens when creating gift code. Please Retry.
	ErrBIZDEGRADATIONERROR                 = "BIZ_DEGRADATION_ERROR"                    // The service is not available now
	ErrBIZINVALIDARGUMENT                  = "BIZ_INVALID_ARGUMENT"                     // Please check whether the input parameter "action" is correct
	ErrBIZINVALIDPRODUCT                   = "BIZ_INVALID_PRODUCT"                      // Invalid product
	ErrBIZLIVENOTFOUND                     = "BIZ_LIVE_NOT_FOUND"                       // The live room does not exist
	ErrBIZNOTLIVEPRODUCT                   = "BIZ_NOT_LIVE_PRODUCT"                     // It is not a product of the live room
	ErrBIZUSERNOTPERMITTED                 = "BIZ_USER_NOT_PERMITTED"                   // No permission
	ErrCAGENOTFOUND                        = "CAGE_NOT_FOUND"                           // Cage not found: {cageNumber}
	ErrCANNOTINBOUNDCANCELLEDTASK          = "CANNOT_INBOUND_CANCELLED_TASK"            // Tracking number {trackingNumber} is cancelled. Please remove out of list
	ErrDOPMERCHANTMDOP                     = "DOP_MERCHANT_MDOP"                        // Seller is a MDOP, your parcel cannot be dropped-off to any station. DOP Merchant={sellerName}, and TN={trackingNumber}
	ErrDOPPARCELSTATUSNOTWHITELIST         = "DOP_PARCEL_STATUS_NOT_WHITELIST"          // Parcel is not at correct status to dropoff, parcel {trackingNumber} is now {status}
	ErrDOPRESERVEDPARCELNOTFOUND           = "DOP_RESERVED_PARCEL_NOT_FOUND"            // No parcel info for tracking number {trackingNumber}. Please scan again or manually input the tracking number.
	ErrDropshippingInvalid                 = "Dropshipping invalid"                     // input orderId: Own Warehouse invalid
	ErrDUPLICATEREQUEST                    = "DUPLICATE_REQUEST"                        // Your request is processing
	ErrE0207                               = "E0207"                                    // "E207: SKU not exist"
	ErrE0208                               = "E0208"                                    // Product not exist
	ErrE1000                               = "E1000"                                    // Internal Application Error
	ErrE1001                               = "E1001"                                    // not jit seller
	ErrE1002                               = "E1002"                                    // not jit product
	ErrECONCILIATIONCSVERRORFAILED         = "ECONCILIATION_CSV_ERROR_FAILED"           // Error happens when creating reconciliation file.
	ErrFAILTOADDVIDEO                      = "FAIL_TO_ADD_VIDEO"                        // detail message
	ErrFAILTOBLOCKCOMPLETE                 = "FAIL_TO_BLOCK_COMPLETE"                   // detail message
	ErrFAILTOBLOCKINIT                     = "FAIL_TO_BLOCK_INIT"                       // detail message
	ErrFAILTODELETEVIDEO                   = "FAIL_TO_DELETE_VIDEO"                     // detail message
	ErrFAILTOGETSHOPINFO                   = "FAIL_TO_GET_SHOP_INFO"                    // detail message
	ErrFAILTOGETUSERCAPACITY               = "FAIL_TO_GET_USER_CAPACITY"                // more detail
	ErrFAILTOGETVIDEO                      = "FAIL_TO_GET_VIDEO"                        // detail message
	ErrFAILTOUPLOADBLOCK                   = "FAIL_TO_UPLOAD_BLOCK"                     // detail message
	ErrFAILTOVALIDATE                      = "FAIL_TO_VALIDATE"                         // detail message
	ErrGIFTCODELOCKCONFLICT                = "GIFT_CODE_LOCK_CONFLICT"                  // Gift code is already being created，please wait for a moment and check the batch list
	ErrGIFTCODEQUERYEMPTY                  = "GIFT_CODE_QUERY_EMPTY"                    // There are no such gift code
	ErrHttpConnectError                    = "HttpConnectError"                         // Request failed, due to [%s]
	ErrILLEGALPARAMETER                    = "ILLEGAL_PARAMETER"                        // detail message
	ErrIllegalAccessToken                  = "IllegalAccessToken"                       // The specified access token is invalid or expired
	ErrINPUTPARAMVALID                     = "INPUT_PARAM_VALID"                        // query trade failed
	ErrINTERNALSYSTEMERROR                 = "INTERNAL_SYSTEM_ERROR"                    // Internal system error. Please try again
	ErrINVALIDADDRESSID                    = "INVALID_ADDRESS_ID"                       // Provided address ID is not valid
	ErrINVALIDSTATUSFORBIDDENPICKUP        = "INVALID_STATUS_FORBIDDEN_PICK_UP"         // INVALID_STATUS_FORBIDDEN_PICK_UP
	ErrInvalidParameter                    = "InvalidParameter"                         // The specified parameter “null#addressId” is not valid
	ErrLDINPUTPARAMVALID                   = "LD_INPUT_PARAM_VALID"                     // orderId is wrong
	ErrLDINVOKEDOWNSTREAMRESPONSEBLANK     = "LD_INVOKE_DOWNSTREAM_RESPONSE_BLANK"      // LD_INVOKE_DOWNSTREAM_RESPONSE_BLANK
	ErrLZDMEMBERUSER1011                   = "LZD_MEMBER_USER_1011"                     // LZD_MEMBER_USER_1011
	ErrMp3SellerApiLimit                   = "Mp3SellerApiLimit"                        // Mp3 Seller not support the api -apipath
	ErrNOROUTEERROR                        = "NO_ROUTE_ERROR"                           // No suitable route found
	ErrOPENAPICALLEXCEEDLIMIT              = "OPEN_API_CALL_EXCEED_LIMIT"               // Open Api call times exceeds: apiName_limitType
	ErrOPENAPITIMESTAMPINVALID             = "OPEN_API_TIMESTAMP_INVALID"               // The input timestamp is invalid
	ErrOPENDIRECTTRANSFERINTERNALFAIL      = "OPEN_DIRECT_TRANSFER_INTERNAL_FAIL"       // Direct transfer internal error, please retry or contact lazada tech team.
	ErrOPENDIRECTTRANSFERLOCKCONFLICT      = "OPEN_DIRECT_TRANSFER_LOCK_CONFLICT"       // Direct transfer request is already being processed，please wait for a moment and check status
	ErrP08800000015170                     = "P-088-0000-00-15-170"                     // seller has stores that are not packaged across stores
	ErrP08800000015195                     = "P-088-0000-00-15-195"                     // query lzd merchant seller not found
	ErrP08800000015205                     = "P-088-0000-00-15-205"                     // param is null
	ErrP08800000015209                     = "P-088-0000-00-15-209"                     // handover content not found
	ErrP08800000015213                     = "P-088-0000-00-15-213"                     // param country is null
	ErrP08800000015214                     = "P-088-0000-00-15-214"                     // param province is null
	ErrP08800000015215                     = "P-088-0000-00-15-215"                     // param city is null
	ErrP08800000015216                     = "P-088-0000-00-15-216"                     // param detailAddress is null
	ErrP08800000015217                     = "P-088-0000-00-15-217"                     // param country is not support
	ErrP08800000015218                     = "P-088-0000-00-15-218"                     // params is null
	ErrP08800000015231                     = "P-088-0000-00-15-231"                     // pick up collection point info missing
	ErrP08800000015300                     = "P-088-0000-00-15-300"                     // handover content status not committed、awaiting_tracking_number or awaiting_pickup, can not update
	ErrP08801011010140                     = "P-088-0101-10-10-140"                     // all parcel order not found
	ErrP08801011010152                     = "P-088-0101-10-10-152"                     // address service result error
	ErrP08801011010191                     = "P-088-0101-10-10-191"                     // query across store account not found
	ErrP08801011010192                     = "P-088-0101-10-10-192"                     // query across account relation not found
	ErrPARAMILLEGAL                        = "PARAM_ILLEGAL"                            // "sku not exists"
	ErrPARAMSVALIDATEERROR                 = "PARAMS_VALIDATE_ERROR"                    // NULL_SELLERID
	ErrPARCELALREADYINBOUND                = "PARCEL_ALREADY_INBOUND"                   // Parcel has already inbounded: {trackingNumber}
	ErrPARCELNOTFOUND                      = "PARCEL_NOT_FOUND"                         // Parcel not found: {trackingNumber1,trackingNumber2}
	ErrPARTIALDELIVERYNOTAVAILABLE         = "PARTIAL_DELIVERY_NOT_AVAILABLE"           // Partial Delivery is not available because out of Lex coverage
	ErrPARTNERNOTFOUND                     = "PARTNER_NOT_FOUND"                        // No partner matches with provided information
	ErrPROCEEDTRANSFEREXCEPTION            = "PROCEED_TRANSFER_EXCEPTION"               // Internal error, please retry or contact lazada tech team.
	ErrRECONCILIATIONINPUTDATEINVALID      = "RECONCILIATION_INPUT_DATE_INVALID"        //  Invalid input format of local date.
	ErrRISKREJECT                          = "RISK_REJECT"                              // The transfer recipient's account status is abnormal, please check
	ErrSellerNotVerified                   = "SellerNotVerified"                        // Seller not verified,please check seller status
	ErrServiceTimeout                      = "ServiceTimeout"                           // The request has failed due to service timeout
	ErrSTATIONISNOTDOP                     = "STATION_IS_NOT_DOP"                       // Station {stationCode} is not a DOP. You can not drop-off here.
	ErrSTATIONNOTACTIVE                    = "STATION_NOT_ACTIVE"                       // Station [{stationCode}] is not active
	ErrSYSTEMERROR                         = "SYSTEM_ERROR"                             // We are experiencing a surge in traffic. Please try again. If you continue to get this message, try again later
	ErrTRAFFICCONTROL                      = "TRAFFIC_CONTROL"                          // TRAFFIC_CONTROL
	ErrTRANSFERAMOUNTEXCEEDLIMIT           = "TRANSFER_AMOUNT_EXCEED_LIMIT"             // The transfer amount has exceeded the limit.
	ErrTRANSFERERRORACCOUNTNUMBERINVALID   = "TRANSFER_ERROR_ACCOUNT_NUMBER_INVALID"    // Account number is invalid
	ErrTRANSFERERRORMSGAMOUNTINVALID       = "TRANSFER_ERROR_MSG_AMOUNT_INVALID"        // Amount is invalid
	ErrTRANSFERERRORMSGQUANTITYINVALID     = "TRANSFER_ERROR_MSG_QUANTITY_INVALID"      // The quantity of gift code is invalid
	ErrTRANSFERERRORMSGRESPONSEDFAILED     = "TRANSFER_ERROR_MSG_RESPONSED_FAILED"      // Error happens when transferring，please contact lazada team
	ErrTRANSFERERRORMSGUSERNOTFOUND        = "TRANSFER_ERROR_MSG_USER_NOT_FOUND"        // User to be transferred not found.
	ErrTRANSFERERRORMSGWALLETINACTIVATED   = "TRANSFER_ERROR_MSG_WALLET_INACTIVATED"    // The transfer account has not activated the wallet
	ErrTRANSFERERRORNATIONNOTINLIST        = "TRANSFER_ERROR_NATION_NOT_IN_LIST"        // The current user's region does not have permission to access, please contact the lazada tech team.
	ErrTRANSFERERRORTRANSFERORDERIDINVALID = "TRANSFER_ERROR_TRANSFER_ORDER_ID_INVALID" // Transfer order ID is invalid
	ErrTRANSFERISCORPORATEUSERERROR        = "TRANSFER_IS_CORPORATE_USER_ERROR"         // The recipient account is corporate user.
	ErrTRANSFERUSERUNMATCHED               = "TRANSFER_USER_UNMATCHED"                  // User to be transferred not match
	ErrTRANSFERVALUEUNMATCHED              = "TRANSFER_VALUE_UNMATCHED"                 // Transfer amount does not match
	ErrTRANSFERWITHDRAWABLEUNMATCHED       = "TRANSFER_WITHDRAWABLE_UNMATCHED"          // Transfer withdrawable does not match.
	ErrUNEXPECTEDERROR                     = "UNEXPECTED_ERROR"                         // NullpointerException
	ErrUnknownRuntimeException             = "UnknownRuntimeException"                  // The request has failed due to RPC runtime failure
	ErrUSERBALANCENOTENOUGH                = "USER_BALANCE_NOT_ENOUGH"                  // The available deposit is not enough for the transfer.
	ErrUSERISNOTLOGGEDIN                   = "USER_IS_NOT_LOGGED_IN"                    // The user is not logged in
)
