package golazada

const (
	Err00                                  = "00"                                       // sucess
	Err01                                  = "01"                                       // cancel success
	Err02                                  = "02"                                       // update serviceDate success
	Err1                                   = "1"                                        // E001: Parameter %s is mandatory
	Err100                                 = "100"                                      // E0100: reverse order list is empty
	Err1000                                = "1000"                                     // Internal Application Error
	Err1000012                             = "1000012"                                  // endTime - startTime must should be less than 180 days
	Err1000014                             = "1000014"                                  // Can not find that transactionType
	Err10001                               = "10001"                                    // Illegal parameters
	Err10002                               = "10002"                                    // Incorrect/missing/unavailable product attributes
	Err10003                               = "10003"                                    // Item not found
	Err10004                               = "10004"                                    // price need to be lower than the original price
	Err10005                               = "10005"                                    // 商品已升级
	Err10006                               = "10006"                                    // the control price is not pass
	Err1001                                = "1001"                                     // The parameters are not in JSON format
	Err1003                                = "1003"                                     // E1003_3PL_ALLOCATION_FAIL
	Err101                                 = "101"                                      // E101: Redemption Operator Invalid
	Err102                                 = "102"                                      // E0102: trade order line id is empty or invalid
	Err103                                 = "103"                                      // E0103: reverse order line id is empty when query reject reason
	Err104                                 = "104"                                      // E0104: reason is empty or invalid
	Err105                                 = "105"                                      // E0105: reverse order id is empty or invalid
	Err106                                 = "106"                                      // E0106: ROC internal error
	Err107                                 = "107"                                      // E0107: invalid action
	Err108                                 = "108"                                      // E0108: reason can't be empty if you want to refuse return or refund
	Err109                                 = "109"                                      // E0109: comment can't be empty if startDispute
	Err11                                  = "11"                                       // orderNo is empty
	Err110                                 = "110"                                      // E0110: image can't be empty if startDispute
	Err111                                 = "111"                                      // E0111: do not support massive reverse order line operation if you want to refuse return or refund
	Err112                                 = "112"                                      // E0112: no reverse order found
	Err113                                 = "113"                                      // E0113: reverse order line have unknown status
	Err114                                 = "114"                                      // E0114: this reverse does not support this action
	Err115                                 = "115"                                      // E0115: order id is null
	Err116                                 = "116"                                      // E0116: no seller id
	Err117                                 = "117"                                      // E0117: no user id
	Err118                                 = "118"                                      // E0118: no user email
	Err119                                 = "119"                                      // E0119: cannot find any cancel reasons for these orders
	Err12                                  = "12"                                       // thirdOrderNo is empty
	Err120                                 = "120"                                      // E0120: page size invalid
	Err121                                 = "121"                                      // E0121: page number invalid
	Err122                                 = "122"                                      // E0122: invalid trade order
	Err123                                 = "123"                                      // E0123: invalid trade order lines %s
	Err124                                 = "124"                                      // E0124: invalid seller id for this order line %s
	Err125                                 = "125"                                      // E0125: invalid reverse id
	Err126                                 = "126"                                      // E0126: invalid reverse order lines
	Err127                                 = "127"                                      // E0127: invalid seller id for this reverse order line
	Err13                                  = "13"                                       // type is empty
	Err131                                 = "131"                                      // E0131: no decision for this reverse order
	Err133                                 = "133"                                      // E0133: do not support batch operation
	Err14                                  = "14"                                       // E014: "%s" Invalid Offset
	Err15                                  = "15"                                       // servicePrice is empty
	Err16                                  = "16"                                       // E016: "%s" Invalid Order ID
	Err17                                  = "17"                                       // E017: "%s" Invalid Date Format
	Err19                                  = "19"                                       // E019: "%s" Invalid Limit
	Err20                                  = "20"                                       // E020: "%s" Invalid Order Item IDs
	Err200                                 = "200"                                      // E200: Empty SellerSku
	Err201                                 = "201"                                      // E201: %s Invalid CategoryId
	Err202                                 = "202"                                      // E202: %s Invalid SPUId
	Err203                                 = "203"                                      // E203: Too many images in one SKU
	Err204                                 = "204"                                      // E204: Too many SKU in one request
	Err205                                 = "205"                                      // E205: SPU does not exist
	Err206                                 = "206"                                      // E206: Different category id in SPU and PrimaryCategory
	Err207                                 = "207"                                      // E207: SKU not exist
	Err208                                 = "208"                                      // E208: Item not exist
	Err209                                 = "209"                                      // Invalid variation
	Err21                                  = "21"                                       // E021: Internal System Error
	Err212                                 = "212"                                      // Sellable inventory cannot be negative
	Err22                                  = "22"                                       // E022: "%s"
	Err23                                  = "23"                                       // E023: activate failed
	Err24                                  = "24"                                       // E024: Parameter illegal
	Err25                                  = "25"                                       // E025: UMP Exception
	Err26                                  = "26"                                       // E026: Seller Unauthorized
	Err30                                  = "30"                                       // E030: Empty Request
	Err300                                 = "300"                                      // E300: Upload Image Failed
	Err30012                               = "30012"                                    // rts package not found
	Err301                                 = "301"                                      // Migrate Image Failed
	Err302                                 = "302"                                      // Not supported URL
	Err303                                 = "303"                                      // E303: The image is too large
	Err304                                 = "304"                                      // Get Response Failed
	Err306                                 = "306"                                      // E306: attribute tag not allowed
	Err309                                 = "309"                                      // Video id status is not audit success
	Err31                                  = "31"                                       // parse extendInfo to map fail
	Err32                                  = "32"                                       // E032: Document type "%s" is not valid
	Err34                                  = "34"                                       // E034: Order Item must be packed. Please call SetStatusToReadyToShip before
	Err35                                  = "35"                                       // E035: "%s" was not found
	Err36                                  = "36"                                       // E036: Invalid status filter
	Err37                                  = "37"                                       // E037: One or more order id in the list are incorrect
	Err38                                  = "38"                                       // E038: Too many orders were requested
	Err39                                  = "39"                                       // E039: No orders were found
	Err40011                               = "40011"                                    // RPC_ERROR
	Err4104                                = "4104"                                     // BIZ_CHECK_PRICE_PRECISION_INVALID
	Err4105                                = "4105"                                     // BIZ_CHECK_SELLER_SKU_DUPLICATE
	Err4106                                = "4106"                                     // CHK_CATPROP_CPV_INPUT_SIZE_LIMIT
	Err4107                                = "4107"                                     // CHECK_CAT_PROP_INVALID_NUMBER
	Err4108                                = "4108"                                     // CHK_BASIC_REQUIRED
	Err4109                                = "4109"                                     // CHK_SKU_PROPS_NOT_MATCH_SALE_PROP
	Err4110                                = "4110"                                     // BIZ_CHECK_CAT_PROP_MANDATORY
	Err4111                                = "4111"                                     // CHK_CATPROP_CPV_TEXT_REPEAT
	Err4112                                = "4112"                                     // CHK_SKU_PROPS_DUPLICATE
	Err4113                                = "4113"                                     // CHK_SKU_PROPS_NOT_IDENTICAL
	Err4114                                = "4114"                                     // BIZ_CHECK_PRICE_SAMPLE_NON_ZERO
	Err4115                                = "4115"                                     // CHK_CATPROP_CPV_NOT_ENUM
	Err4116                                = "4116"                                     // BIZ_CHECK_MAIN_IMAGE_DUPLICATE
	Err4117                                = "4117"                                     // BIZ_CHECK_SPECIAL_PRICE_FROM_DATE_AFTER_TO_DATE
	Err4118                                = "4118"                                     // BIZ_CHECK_PRICE_IS_ZERO
	Err4119                                = "4119"                                     // BIZ_CHECK_SPECIAL_PRICE_RATE_OUT_OF_RANGE
	Err4120                                = "4120"                                     // CHK_CATPROP_CPV_MAX_LEGNTH
	Err4121                                = "4121"                                     // BIZ_CHECK_SPECIAL_PRICE_PRECISION_INVALID
	Err4122                                = "4122"                                     // BIZ_CHECK_VIRTUAL_BUNDLE_SKU_SUB_OVER_LIMIT
	Err4123                                = "4123"                                     // BIZ_CHECK_MANGROVE_RULE
	Err4124                                = "4124"                                     // BIZ_CHECK_MANGROVE_RULE_QC
	Err4125                                = "4125"                                     // THD_IC_F_IC_DOMAIN_PROPERTY_002
	Err4126                                = "4126"                                     // THD_IC_F_IC_INFRA_PRODUCT_036
	Err4127                                = "4127"                                     // THD_IC_F_IC_SCENE_PUBLISH_012
	Err4128                                = "4128"                                     // THD_IC_F_IC_DOMAIN_ACTOR_006
	Err4129                                = "4129"                                     // BIZ_CHECK_PROP_SPECIAL_CHAR
	Err4130                                = "4130"                                     // BIZ_CHECK_OFFICIAL_STORE_BRAND_UNAUTHORIZED
	Err4131                                = "4131"                                     // BIZ_CHECK_CAT_PROP_SENSITIVE_WORDS
	Err4132                                = "4132"                                     // Invalid Request Format
	Err4133                                = "4133"                                     // Invalid variation
	Err4134                                = "4134"                                     // Please select the last level category.
	Err4135                                = "4135"                                     // THD_IC_ERR
	Err4136                                = "4136"                                     // SELLER_SKU_NOT_FOUND
	Err4137                                = "4137"                                     // ITEM_NOT_FOUND
	Err4138                                = "4138"                                     // BIZ_CHECK_EXIST_OUTER_IMAGE
	Err4139                                = "4139"                                     // BIZ_CHECK_MAIN_IMAGE_REQUIRE
	Err4140                                = "4140"                                     // CHK_ENUM_PROP_VALUE_NOT_IN_OPTION
	Err4141                                = "4141"                                     // THD_IC_ERR_F_IC_INFRA_PRODUCT_036
	Err4142                                = "4142"                                     // THD_BRAND_ID_IS_NOT_VALID_IN_CATEGORY
	Err4143                                = "4143"                                     // BIZ_CHECK_SALEPROP_ATTRIBUTE_INVALID
	Err4144                                = "4144"                                     // BIZ_CHECK_SKU_NOT_CONTAIN_SALEPROP
	Err4145                                = "4145"                                     // BIZ_CHECK_SALEPROP_AND_OLD_PARAM_REPEAT
	Err4146                                = "4146"                                     // BIZ_CHECK_SALEPROP_NOT_SUPPORT_THUMBNAIL
	Err4147                                = "4147"                                     // THD_IC_ERR_F_IC_SERVICE_EDIT_002
	Err4148                                = "4148"                                     // BIZ_CHECK_ITEM_HAS_REACH_LIMIT
	Err4149                                = "4149"                                     // BIZ_CHECK_PACKAGE_DECIMAL_INVALID
	Err4150                                = "4150"                                     // SELLER_SKU_INVALID
	Err4151                                = "4151"                                     // BIZ_CHECK_MTEE_RULE_QC
	Err4152                                = "4152"                                     // THD_INVENTORY_ERR_INV_PARAM_ILLEGAL
	Err4153                                = "4153"                                     // THD_IC_ERR_FC_IC_SKU_IMAGE_001
	Err4154                                = "4154"                                     // SYS_REQUEST_TOO_FAST
	Err4155                                = "4155"                                     // BIZ_CHECK_NO_EDIT_ITEM_LOCK
	Err4156                                = "4156"                                     // C035: No brand cannot be selected
	Err4157                                = "4157"                                     // BIZ_CHECK_SPECIAL_PRICE_GREATER_THAN_PRICE
	Err4158                                = "4158"                                     // THD_IC_ERR_F_DOMAIN_IMAGE_00_01_003
	Err4159                                = "4159"                                     // IC_EXCEPTION
	Err4160                                = "4160"                                     // THD_IC_ERR_F_PRODUCT_00_15_004
	Err4161                                = "4161"                                     // VARIATION_CATEGORY_ATTRIBUTE_INVALID
	Err4162                                = "4162"                                     // THD_IC_ERR_F_IC_ABILITY_PG
	Err4163                                = "4163"                                     // BIZ_CHECK_RESTRICTED_CATEGORY
	Err4164                                = "4164"                                     // BIZ_CHECK_MAX_PACKAGE_WEIGHT
	Err4165                                = "4165"                                     // BIZ_CHECK_MAX_PACKAGE_DIMENISIONS
	Err4166                                = "4166"                                     // THD_IC_ERR_F_IC_INFRA_SPU_036
	Err4167                                = "4167"                                     // THD_IC_ERR_F_IC_DOMAIN_PROPERTY_002
	Err4168                                = "4168"                                     // BIZ_CHECK_BRAND_PERMISSION_TIER_TWO
	Err4169                                = "4169"                                     // CHK_IMAGE_MAX_ITEMS
	Err4170                                = "4170"                                     // During the Bday Mega campaign, there are restrictions for stock adjustments in effect between YYYY-MM-DD HH:MM:SS - YYYY-MM-DD HH:MM:SS. Sellers can increase stocks, but may not decrease stocks.
	Err4171                                = "4171"                                     // The updated SKU quantity exceeds the maximum number 50, please do not update more than 50 SKUs at once
	Err4172                                = "4172"                                     // PB_SKU_PROP_REQUIRED
	Err4173                                = "4173"                                     // PB_NO_PROPER_SKU
	Err4174                                = "4174"                                     // E4174
	Err4175                                = "4175"                                     // E4175
	Err4176                                = "4176"                                     // E4176
	Err4177                                = "4177"                                     // E4177
	Err4178                                = "4178"                                     // E4178
	Err4179                                = "4179"                                     // E4179
	Err4180                                = "4180"                                     // E4180
	Err4181                                = "4181"                                     // E4181
	Err4182                                = "4182"                                     // E4182
	Err4183                                = "4183"                                     // E4183
	Err4184                                = "4184"                                     // E4184
	Err4185                                = "4185"                                     // E4185
	Err4186                                = "4186"                                     // PB_ORIGIN_SALE_PRICE_CANNOT_BE_EMPTY
	Err4187                                = "4187"                                     // E4187
	Err4188                                = "4188"                                     // PB_MARKET_PRICE_CANNOT_BE_EMPTY
	Err4189                                = "4189"                                     // E4189
	Err4190                                = "4190"                                     // E4190
	Err4191                                = "4191"                                     // PB_STOCK_CANNOT_BE_EMPTY
	Err4192                                = "4192"                                     // PB_STOCK_INVALID
	Err4193                                = "4193"                                     // The SellerSku parameter is no longer supported. Please update your parameter to use SkuId and try again
	Err4194                                = "4194"                                     // PB_SELLER_SKU_EXIST
	Err4195                                = "4195"                                     // PB_SELLER_SKU_LENGTH_ERROR
	Err4196                                = "4196"                                     // PB_SELLER_SKU_DUPLICATE
	Err4197                                = "4197"                                     // PB_SELLER_SKU_INVALID
	Err4198                                = "4198"                                     // PB_SELLER_SKU_CANNOT_BE_REVISED
	Err4199                                = "4199"                                     // PB_PACKAGE_UNMATCHED
	Err4200                                = "4200"                                     // IMAP_BRAND_NOT_MATCHED
	Err4201                                = "4201"                                     // IMAP_SALE_PROP_UNMATCHED
	Err4202                                = "4202"                                     // IMAP_SALE_PROP_ERR_MATCHED
	Err4203                                = "4203"                                     // IMAP_DEST_SALE_PROP_IS_SPU
	Err4204                                = "4204"                                     // IMAP_SALE_PROP_VAL_ERR_MATCHED
	Err4205                                = "4205"                                     // INVALID_IMAGE_FORMAT
	Err4206                                = "4206"                                     // INVALID_IMAGE_DIMENSION
	Err4207                                = "4207"                                     // IMPORT_SELLER_SKU_EMPTY
	Err4208                                = "4208"                                     // IMPORT_SELLER_SKU_INVALID
	Err4209                                = "4209"                                     // INVALID_CATEGORY
	Err4210                                = "4210"                                     // FAIL_TO_GET_CATEGORY_ID
	Err4211                                = "4211"                                     // HAZMAT_WARN
	Err4212                                = "4212"                                     // PDT_LIMIT_REACH
	Err4213                                = "4213"                                     // MIGRAGE_IMAGE_FAILED
	Err4214                                = "4214"                                     // PG_NOT_PERMIT
	Err4215                                = "4215"                                     // DECO_CREATE_ERROR
	Err4216                                = "4216"                                     // skuId is a mandatory field and must be filled in.
	Err4217                                = "4217"                                     // DECO_SOURCE_QUERY_ERROR
	Err4218                                = "4218"                                     // Update product failed
	Err4219                                = "4219"                                     // DECO_SYNC_ERROR
	Err4220                                = "4220"                                     // TRANSLATE_OVER_FLOW
	Err4221                                = "4221"                                     // BIZ_CHECK_MTEE_RISK_RULE_TRIGGER_MTEE_RISK_RULE_TRIGGER_ERROR
	Err4222                                = "4222"                                     // NO_SKU_COULD_BE_UPDATE
	Err4223                                = "4223"                                     // PRODUCT_NUM_REACH_LIMITATION
	Err4224                                = "4224"                                     // SELLER_STATUS_INVALID
	Err4225                                = "4225"                                     // Your product participated in semi-hosted program, please go to GSP to edit the product price/stock/package details information.
	Err4226                                = "4226"                                     // SELLER_PUNISHMENT_INVALID
	Err4227                                = "4227"                                     // Query category is null
	Err4228                                = "4228"                                     // Query category is not active
	Err4229                                = "4229"                                     // PROHIBITED_BRAND
	Err4230                                = "4230"                                     // PROHIBITED_KEYWORD
	Err5                                   = "5"                                        // E005: Invalid Request Format
	Err500                                 = "500"                                      // E500: Create product failed
	Err50008                               = "50008"                                    // ot support operation for sof order
	Err501                                 = "501"                                      // E501: Update product failed
	Err502                                 = "502"                                      // E502: Search SPU failed
	Err503                                 = "503"                                      // E503: Remove product failed
	Err504                                 = "504"                                      // E504: Set product Image failed
	Err506                                 = "506"                                      // E506: Get product failed
	Err512                                 = "512"                                      // E512: BIZ_CHECK_MANGROVE_RULE_QC
	Err513                                 = "513"                                      // Internal call exception
	Err56                                  = "56"                                       // E056: Invalid OrdersIdList format. Must use array format [1,2]
	Err57                                  = "57"                                       // E057: No attribute sets linked to that category.
	Err6                                   = "6"                                        // E006: Unexpected internal error
	Err70                                  = "70"                                       // E070: You have corrupt data in your sku seller list.
	Err700000                              = "700000"                                   // PACKAGE_STATUS_NOT_ALLOW_TO_OP
	Err700001                              = "700001"                                   // DBS_SHIPMENT_PROVIDER_CODE_NOT_EXITS
	Err700004                              = "700004"                                   //  PARAM_ILLEGAL
	Err700013                              = "700013"                                   // OP_NOT_SUPPORT
	Err700016                              = "700016"                                   // NOT_AVAILABLE_NTFS_3PL
	Err700017                              = "700017"                                   // PARAM_IS_NULL
	Err700018                              = "700018"                                   //  PARAM_SIZE_ERROR
	Err700019                              = "700019"                                   // PARAM_MIN_ERROR
	Err700020                              = "700020"                                   // ORDER_ITEM_NOT_FOUND_OR_NOT_BELONG_DIGITAL
	Err700021                              = "700021"                                   //  ORDER_NOT_FOUND
	Err700022                              = "700022"                                   // BATCH_SIZE_OUT_OF_LIMIT
	Err700023                              = "700023"                                   //  PICKUP_IN_STORE_NO_SUPPORT
	Err700024                              = "700024"                                   // GET_LOCK_FAILED
	Err700025                              = "700025"                                   // ORDER_ITEM_NOT_FOUND
	Err700026                              = "700026"                                   // FO_ITEM_NOT_ALLOW_TO_PACK
	Err700027                              = "700027"                                   // NOT_SUPPORT_FBL_TO_PACK
	Err700028                              = "700028"                                   // NOT_SUPPORT_PACK_UP_IN_STORE_TO_PACK
	Err700029                              = "700029"                                   //  ITEM_MUST_BELONG_SAME_WAREHOUSE
	Err700030                              = "700030"                                   //  NOT_SUPPORT_DG_SERVICE_TO_PACK
	Err700031                              = "700031"                                   //  ITEM_NOT_READY_TO_FULFILL
	Err700032                              = "700032"                                   // SELLER_NOT_FOUND
	Err700033                              = "700033"                                   // TRANSFERRING_WAREHOUSE_PROVIDER
	Err700040                              = "700040"                                   // There are no packages that support printing!
	Err701                                 = "701"                                      // E701: Empty category suggestion.
	Err74                                  = "74"                                       // E074: Invalid sort direction.
	Err75                                  = "75"                                       // E075: Invalid sort filter.
	Err901                                 = "901"                                      // E901: The request is too frequent, or the requested functionality is temporarily disabled.
	Err99                                  = "99"                                       // fail
	ErrAPPKEYINVALID                       = "APP_KEY_INVALID"                          // App key is invalid, please contact lazada tech team.
	ErrBADREQUEST                          = "BAD_REQUEST"                              // Invalid request
	ErrBALANCEACCOUNTNOTENOUGH             = "BALANCE_ACCOUNT_NOT_ENOUGH"               // Balance account is not enough.
	ErrBATCHCREATEERROR                    = "BATCH_CREATE_ERROR"                       // Error happens when creating gift code. Please Retry.
	ErrBIZDEGRADATIONERROR                 = "BIZ_DEGRADATION_ERROR"                    // The service is not available now
	ErrBIZINVALIDARGUMENT                  = "BIZ_INVALID_ARGUMENT"                     // Please check whether the input parameter "action" is correct
	ErrBIZINVALIDPRODUCT                   = "BIZ_INVALID_PRODUCT"                      // Invalid product
	ErrBIZLIVENOTFOUND                     = "BIZ_LIVE_NOT_FOUND"                       // The live room does not exist
	ErrBIZNOTLIVEPRODUCT                   = "BIZ_NOT_LIVE_PRODUCT"                     // It is not a product of the live room
	ErrBIZUSERNOTPERMITTED                 = "BIZ_USER_NOT_PERMITTED"                   // No permission
	ErrCAGENOTFOUND                        = "CAGE_NOT_FOUND"                           // Cage not found: {cageNumber}
	ErrCANNOTINBOUNDCANCELLEDTASK          = "CANNOT_INBOUND_CANCELLED_TASK"            // Tracking number {trackingNumber} is cancelled. Please remove out of list
	ErrDOPMERCHANTMDOP                     = "DOP_MERCHANT_MDOP"                        // Seller is a MDOP, your parcel cannot be dropped-off to any station. DOP Merchant={sellerName}, and TN={trackingNumber}
	ErrDOPPARCELSTATUSNOTWHITELIST         = "DOP_PARCEL_STATUS_NOT_WHITELIST"          // Parcel is not at correct status to dropoff, parcel {trackingNumber} is now {status}
	ErrDOPRESERVEDPARCELNOTFOUND           = "DOP_RESERVED_PARCEL_NOT_FOUND"            // No parcel info for tracking number {trackingNumber}. Please scan again or manually input the tracking number.
	ErrDropshippingInvalid                 = "Dropshipping invalid"                     // input orderId: Own Warehouse invalid
	ErrDUPLICATEREQUEST                    = "DUPLICATE_REQUEST"                        // Your request is processing
	ErrE0001                               = "E0001"                                    // Parameter ItemId is mandatory
	ErrE0002                               = "E0002"                                    // Product not exists
	ErrE0003                               = "E0003"                                    // Seller Sku not exists
	ErrE0004                               = "E0004"                                    // Product Status not online
	ErrE0006                               = "E0006"                                    // Unexpected internal error
	ErrE0207                               = "E0207"                                    // "E207: SKU not exist"
	ErrE0208                               = "E0208"                                    // Product not exist
	ErrE1000                               = "E1000"                                    // Internal Application Error
	ErrE1001                               = "E1001"                                    // not jit seller
	ErrE1002                               = "E1002"                                    // not jit product
	ErrECONCILIATIONCSVERRORFAILED         = "ECONCILIATION_CSV_ERROR_FAILED"           // Error happens when creating reconciliation file.
	ErrEDITITEMNOTBELONGSELLER             = "EDIT_ITEM_NOT_BELONG_SELLER"              // You are not authorized to edit the item.
	ErrFAILTOADDVIDEO                      = "FAIL_TO_ADD_VIDEO"                        // detail message
	ErrFAILTOBLOCKCOMPLETE                 = "FAIL_TO_BLOCK_COMPLETE"                   // detail message
	ErrFAILTOBLOCKINIT                     = "FAIL_TO_BLOCK_INIT"                       // detail message
	ErrFAILTODELETEVIDEO                   = "FAIL_TO_DELETE_VIDEO"                     // detail message
	ErrFAILTOGETSHOPINFO                   = "FAIL_TO_GET_SHOP_INFO"                    // detail message
	ErrFAILTOGETUSERCAPACITY               = "FAIL_TO_GET_USER_CAPACITY"                // more detail
	ErrFAILTOGETVIDEO                      = "FAIL_TO_GET_VIDEO"                        // detail message
	ErrFAILTOUPLOADBLOCK                   = "FAIL_TO_UPLOAD_BLOCK"                     // detail message
	ErrFAILTOVALIDATE                      = "FAIL_TO_VALIDATE"                         // detail message
	ErrGIFTCODELOCKCONFLICT                = "GIFT_CODE_LOCK_CONFLICT"                  // Gift code is already being created，please wait for a moment and check the batch list
	ErrGIFTCODEQUERYEMPTY                  = "GIFT_CODE_QUERY_EMPTY"                    // There are no such gift code
	ErrHOTKEYBLOCKEXCEPTION                = "HOT_KEY_BLOCK_EXCEPTION"                  // hot key protect
	ErrHttpConnectError                    = "HttpConnectError"                         // Request failed, due to [%s]
	ErrILLEGALPARAMETER                    = "ILLEGAL_PARAMETER"                        // detail message
	ErrIllegalAccessToken                  = "IllegalAccessToken"                       // The specified access token is invalid or expired
	ErrINPUTPARAMVALID                     = "INPUT_PARAM_VALID"                        // query trade failed
	ErrINTERNALSYSTEMERROR                 = "INTERNAL_SYSTEM_ERROR"                    // Internal system error. Please try again
	ErrINVALIDADDRESSID                    = "INVALID_ADDRESS_ID"                       // Provided address ID is not valid
	ErrINVALIDSTATUSFORBIDDENPICKUP        = "INVALID_STATUS_FORBIDDEN_PICK_UP"         // INVALID_STATUS_FORBIDDEN_PICK_UP
	ErrInvalidParameter                    = "InvalidParameter"                         // The specified parameter “null#addressId” is not valid
	ErrLDINPUTPARAMVALID                   = "LD_INPUT_PARAM_VALID"                     // orderId is wrong
	ErrLDINVOKEDOWNSTREAMRESPONSEBLANK     = "LD_INVOKE_DOWNSTREAM_RESPONSE_BLANK"      // LD_INVOKE_DOWNSTREAM_RESPONSE_BLANK
	ErrLZDMEMBERUSER1011                   = "LZD_MEMBER_USER_1011"                     // LZD_MEMBER_USER_1011
	ErrMp3SellerApiLimit                   = "Mp3SellerApiLimit"                        // Mp3 Seller not support the api -apipath
	ErrNOROUTEERROR                        = "NO_ROUTE_ERROR"                           // No suitable route found
	ErrONLYCBSELLERSUPPORTED               = "ONLY_CB_SELLER_SUPPORTED"                 // For now, only cb seller supported
	ErrOPENAPICALLEXCEEDLIMIT              = "OPEN_API_CALL_EXCEED_LIMIT"               // Open Api call times exceeds: apiName_limitType
	ErrOPENAPITIMESTAMPINVALID             = "OPEN_API_TIMESTAMP_INVALID"               // The input timestamp is invalid
	ErrOPENDIRECTTRANSFERINTERNALFAIL      = "OPEN_DIRECT_TRANSFER_INTERNAL_FAIL"       // Direct transfer internal error, please retry or contact lazada tech team.
	ErrOPENDIRECTTRANSFERLOCKCONFLICT      = "OPEN_DIRECT_TRANSFER_LOCK_CONFLICT"       // Direct transfer request is already being processed，please wait for a moment and check status
	ErrP08800000015170                     = "P-088-0000-00-15-170"                     // seller has stores that are not packaged across stores
	ErrP08800000015195                     = "P-088-0000-00-15-195"                     // query lzd merchant seller not found
	ErrP08800000015205                     = "P-088-0000-00-15-205"                     // param is null
	ErrP08800000015209                     = "P-088-0000-00-15-209"                     // handover content not found
	ErrP08800000015213                     = "P-088-0000-00-15-213"                     // param country is null
	ErrP08800000015214                     = "P-088-0000-00-15-214"                     // param province is null
	ErrP08800000015215                     = "P-088-0000-00-15-215"                     // param city is null
	ErrP08800000015216                     = "P-088-0000-00-15-216"                     // param detailAddress is null
	ErrP08800000015217                     = "P-088-0000-00-15-217"                     // param country is not support
	ErrP08800000015218                     = "P-088-0000-00-15-218"                     // params is null
	ErrP08800000015231                     = "P-088-0000-00-15-231"                     // pick up collection point info missing
	ErrP08800000015300                     = "P-088-0000-00-15-300"                     // handover content status not committed、awaiting_tracking_number or awaiting_pickup, can not update
	ErrP08801011010140                     = "P-088-0101-10-10-140"                     // all parcel order not found
	ErrP08801011010152                     = "P-088-0101-10-10-152"                     // address service result error
	ErrP08801011010191                     = "P-088-0101-10-10-191"                     // query across store account not found
	ErrP08801011010192                     = "P-088-0101-10-10-192"                     // query across account relation not found
	ErrPARAMILLEGAL                        = "PARAM_ILLEGAL"                            // "sku not exists"
	ErrPARAMSVALIDATEERROR                 = "PARAMS_VALIDATE_ERROR"                    // NULL_SELLERID
	ErrPARCELALREADYINBOUND                = "PARCEL_ALREADY_INBOUND"                   // Parcel has already inbounded: {trackingNumber}
	ErrPARCELNOTFOUND                      = "PARCEL_NOT_FOUND"                         // Parcel not found: {trackingNumber1,trackingNumber2}
	ErrPARTIALDELIVERYNOTAVAILABLE         = "PARTIAL_DELIVERY_NOT_AVAILABLE"           // Partial Delivery is not available because out of Lex coverage
	ErrPARTNERNOTFOUND                     = "PARTNER_NOT_FOUND"                        // No partner matches with provided information
	ErrPROCEEDTRANSFEREXCEPTION            = "PROCEED_TRANSFER_EXCEPTION"               // Internal error, please retry or contact lazada tech team.
	ErrRECONCILIATIONINPUTDATEINVALID      = "RECONCILIATION_INPUT_DATE_INVALID"        //  Invalid input format of local date.
	ErrRISKREJECT                          = "RISK_REJECT"                              // The transfer recipient's account status is abnormal, please check
	ErrSELLERSERVICEFAIL                   = "SELLER_SERVICE_FAIL"                      // inner service fail
	ErrSellerNotActive                     = "SellerNotActive"                          // Seller not active,please check seller status
	ErrSellerNotVerified                   = "SellerNotVerified"                        // Seller not verified,please check seller status
	ErrServiceTimeout                      = "ServiceTimeout"                           // The request has failed due to service timeout
	ErrSTATIONISNOTDOP                     = "STATION_IS_NOT_DOP"                       // Station {stationCode} is not a DOP. You can not drop-off here.
	ErrSTATIONNOTACTIVE                    = "STATION_NOT_ACTIVE"                       // Station [{stationCode}] is not active
	ErrSYSERROR                            = "SYS_ERROR"                                // inner service fail
	ErrSYSTEMERROR                         = "SYSTEM_ERROR"                             // We are experiencing a surge in traffic. Please try again. If you continue to get this message, try again later
	ErrTHIRDSERVICEERROR                   = "THIRD_SERVICE_ERROR"                      // inner service fail
	ErrTRAFFICCONTROL                      = "TRAFFIC_CONTROL"                          // TRAFFIC_CONTROL
	ErrTRANSFERAMOUNTEXCEEDLIMIT           = "TRANSFER_AMOUNT_EXCEED_LIMIT"             // The transfer amount has exceeded the limit.
	ErrTRANSFERERRORACCOUNTNUMBERINVALID   = "TRANSFER_ERROR_ACCOUNT_NUMBER_INVALID"    // Account number is invalid
	ErrTRANSFERERRORMSGAMOUNTINVALID       = "TRANSFER_ERROR_MSG_AMOUNT_INVALID"        // Amount is invalid
	ErrTRANSFERERRORMSGQUANTITYINVALID     = "TRANSFER_ERROR_MSG_QUANTITY_INVALID"      // The quantity of gift code is invalid
	ErrTRANSFERERRORMSGRESPONSEDFAILED     = "TRANSFER_ERROR_MSG_RESPONSED_FAILED"      // Error happens when transferring，please contact lazada team
	ErrTRANSFERERRORMSGUSERNOTFOUND        = "TRANSFER_ERROR_MSG_USER_NOT_FOUND"        // User to be transferred not found.
	ErrTRANSFERERRORMSGWALLETINACTIVATED   = "TRANSFER_ERROR_MSG_WALLET_INACTIVATED"    // The transfer account has not activated the wallet
	ErrTRANSFERERRORNATIONNOTINLIST        = "TRANSFER_ERROR_NATION_NOT_IN_LIST"        // The current user's region does not have permission to access, please contact the lazada tech team.
	ErrTRANSFERERRORTRANSFERORDERIDINVALID = "TRANSFER_ERROR_TRANSFER_ORDER_ID_INVALID" // Transfer order ID is invalid
	ErrTRANSFERISCORPORATEUSERERROR        = "TRANSFER_IS_CORPORATE_USER_ERROR"         // The recipient account is corporate user.
	ErrTRANSFERUSERUNMATCHED               = "TRANSFER_USER_UNMATCHED"                  // User to be transferred not match
	ErrTRANSFERVALUEUNMATCHED              = "TRANSFER_VALUE_UNMATCHED"                 // Transfer amount does not match
	ErrTRANSFERWITHDRAWABLEUNMATCHED       = "TRANSFER_WITHDRAWABLE_UNMATCHED"          // Transfer withdrawable does not match.
	ErrUNEXPECTEDERROR                     = "UNEXPECTED_ERROR"                         // NullpointerException
	ErrUnknownRuntimeException             = "UnknownRuntimeException"                  // The request has failed due to RPC runtime failure
	ErrUSERBALANCENOTENOUGH                = "USER_BALANCE_NOT_ENOUGH"                  // The available deposit is not enough for the transfer.
	ErrUSERISNOTLOGGEDIN                   = "USER_IS_NOT_LOGGED_IN"                    // The user is not logged in
)
